Added reviews
mitraws/Project-Barangay pull request #26
Opened 2020-10-15 12:41 UTC by vishakahegde

##What this pull request does

- Added reviews to the homepage
- Styled a bit

#Issues

- Slideshow needs a bit of tweaking
- It can be done later too

2020-10-15 14:28 UTC, mitraws commented
Plz show us a screenshot next time =D

2020-10-15 14:30 UTC, mitraws approved these changes
Someone else also approve and merge plz.

2020-10-16 08:34 UTC, jendhordejan requested changes
overall the code looks good but please clean-up unncessary commented lines. if it's really needed to be left there. I suggest putting a note for the reason

2020-10-16 08:34 UTC, jendhordejan commented on src/Components/Pages/Home/HomePage.css
>  /* div {
please delete

2020-10-16 08:34 UTC, jendhordejan commented on src/Components/Pages/Home/HomePage.css
>  /* .row::after {
please delete if not needed

2020-10-16 08:36 UTC, jendhordejan commented on src/Components/Pages/Home/HomePage.css
> +  /* grid-template-rows: 1fr; */
please delete if not needed

2020-10-16 09:10 UTC, mitraws commented on src/Components/Pages/Home/HomePage.css
> +  /* grid-template-rows: 1fr; */
Will do during refactor.

2020-10-16 09:19 UTC, merged